<?php

namespace ContainerOpcCA5E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DRfR0nTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DRfR0nT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DRfR0nT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'stage' => ['privates', 'App\\Repository\\AnimateurRepository', 'getAnimateurRepositoryService', true],
        ], [
            'stage' => 'App\\Repository\\AnimateurRepository',
        ]);
    }
}
