<?php

namespace ContainerOpcCA5E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnimateurTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\AnimateurType' shared autowired service.
     *
     * @return \App\Form\AnimateurType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/AnimateurType.php';

        return $container->privates['App\\Form\\AnimateurType'] = new \App\Form\AnimateurType();
    }
}
