<?php

namespace ContainerNoBe5uP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.iAQmCkv.App\Entity\Stage' shared service.
     *
     * @return \App\Entity\Stage
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.iAQmCkv": it references class "App\\Entity\\Stage" but no such service exists.');
    }
}
