<?php

namespace ContainerLk7ZXXQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZGBdvEAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZGBdvEA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZGBdvEA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'animateur' => ['privates', '.errored..service_locator.ZGBdvEA.App\\Entity\\Animateur', NULL, 'Cannot autowire service ".service_locator.ZGBdvEA": it references class "App\\Entity\\Animateur" but no such service exists.'],
            'animateurRepository' => ['privates', 'App\\Repository\\AnimateurRepository', 'getAnimateurRepositoryService', true],
        ], [
            'animateur' => 'App\\Entity\\Animateur',
            'animateurRepository' => 'App\\Repository\\AnimateurRepository',
        ]);
    }
}
