<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQQxS4xY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQQxS4xY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQQxS4xY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQQxS4xY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQQxS4xY\App_KernelDevDebugContainer([
    'container.build_hash' => 'QQxS4xY',
    'container.build_id' => '4e642229',
    'container.build_time' => 1665481756,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQQxS4xY');
