<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJE6tJR1\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJE6tJR1/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJE6tJR1.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJE6tJR1\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJE6tJR1\App_KernelDevDebugContainer([
    'container.build_hash' => 'JE6tJR1',
    'container.build_id' => 'c4887b22',
    'container.build_time' => 1666787043,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJE6tJR1');
