<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOpcCA5E\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOpcCA5E/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOpcCA5E.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOpcCA5E\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOpcCA5E\App_KernelDevDebugContainer([
    'container.build_hash' => 'OpcCA5E',
    'container.build_id' => '49804490',
    'container.build_time' => 1666115380,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOpcCA5E');
