<?php

namespace ContainerUxQ8xpI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F5hPGkPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F5hPGkP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F5hPGkP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'animateur' => ['privates', '.errored..service_locator.F5hPGkP.App\\Entity\\Animateur', NULL, 'Cannot autowire service ".service_locator.F5hPGkP": it references class "App\\Entity\\Animateur" but no such service exists.'],
        ], [
            'animateur' => 'App\\Entity\\Animateur',
        ]);
    }
}
