<?php

namespace ContainerUxQ8xpI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YxFS003Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YxFS003' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YxFS003'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'animateur' => ['privates', 'App\\Repository\\AnimateurRepository', 'getAnimateurRepositoryService', true],
            'stage' => ['privates', 'App\\Repository\\AnimateurRepository', 'getAnimateurRepositoryService', true],
        ], [
            'animateur' => 'App\\Repository\\AnimateurRepository',
            'stage' => 'App\\Repository\\AnimateurRepository',
        ]);
    }
}
