<?php

namespace ContainerQQxS4xY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IAQmCkvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iAQmCkv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iAQmCkv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'stage' => ['privates', '.errored..service_locator.iAQmCkv.App\\Entity\\Stage', NULL, 'Cannot autowire service ".service_locator.iAQmCkv": it references class "App\\Entity\\Stage" but no such service exists.'],
        ], [
            'stage' => 'App\\Entity\\Stage',
        ]);
    }
}
