<?php

namespace ContainerQQxS4xY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PO1C4MGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PO1C4MG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PO1C4MG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AnimateurController::delete' => ['privates', '.service_locator.ZGBdvEA', 'get_ServiceLocator_ZGBdvEAService', true],
            'App\\Controller\\AnimateurController::edit' => ['privates', '.service_locator.ZGBdvEA', 'get_ServiceLocator_ZGBdvEAService', true],
            'App\\Controller\\AnimateurController::index' => ['privates', '.service_locator.4IwbDDw', 'get_ServiceLocator_4IwbDDwService', true],
            'App\\Controller\\AnimateurController::new' => ['privates', '.service_locator.4IwbDDw', 'get_ServiceLocator_4IwbDDwService', true],
            'App\\Controller\\AnimateurController::show' => ['privates', '.service_locator.F5hPGkP', 'get_ServiceLocator_F5hPGkPService', true],
            'App\\Controller\\StageController::index' => ['privates', '.service_locator.iAQmCkv', 'get_ServiceLocator_IAQmCkvService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\AnimateurController:delete' => ['privates', '.service_locator.ZGBdvEA', 'get_ServiceLocator_ZGBdvEAService', true],
            'App\\Controller\\AnimateurController:edit' => ['privates', '.service_locator.ZGBdvEA', 'get_ServiceLocator_ZGBdvEAService', true],
            'App\\Controller\\AnimateurController:index' => ['privates', '.service_locator.4IwbDDw', 'get_ServiceLocator_4IwbDDwService', true],
            'App\\Controller\\AnimateurController:new' => ['privates', '.service_locator.4IwbDDw', 'get_ServiceLocator_4IwbDDwService', true],
            'App\\Controller\\AnimateurController:show' => ['privates', '.service_locator.F5hPGkP', 'get_ServiceLocator_F5hPGkPService', true],
            'App\\Controller\\StageController:index' => ['privates', '.service_locator.iAQmCkv', 'get_ServiceLocator_IAQmCkvService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\AnimateurController::delete' => '?',
            'App\\Controller\\AnimateurController::edit' => '?',
            'App\\Controller\\AnimateurController::index' => '?',
            'App\\Controller\\AnimateurController::new' => '?',
            'App\\Controller\\AnimateurController::show' => '?',
            'App\\Controller\\StageController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AnimateurController:delete' => '?',
            'App\\Controller\\AnimateurController:edit' => '?',
            'App\\Controller\\AnimateurController:index' => '?',
            'App\\Controller\\AnimateurController:new' => '?',
            'App\\Controller\\AnimateurController:show' => '?',
            'App\\Controller\\StageController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
